export const PATH_NAMES = {
  ADMIN: 'admin',
  ADMIN_ACCESS_DENIED: 'access-denied',
  ADMIN_CMS: 'cms',
  ADMIN_CMS_CONTENT_OPERATIONS: 'content-operations',
  ADMIN_CMS_CALENDAR: 'calendar',
  ADMIN_MEDIA_LIBRARY: 'media-library',
  ADMIN_CMS_HOMEPAGE: 'homepage',
  ADMIN_CMS_TOPICS: 'topics',
  ADMIN_CMS_RECOMMENDED_LINKS: 'recommended-links',
  ADMIN_COMMENTS: 'comments',
  ADMIN_USERS: 'users',
  BLOG: 'blog',
  CAT_CORNER: 'cat-corner',
  CAT_CORNER_UNLOCK: 'unlock',
  SEARCH: 'search',
  LABS: 'labs',
  TOPICS: 'topics',
  LOGOUT: 'logout',
  PROFILE: 'profile',
  OS_MAIN: 'os',
  OS_DEVICE_REQUIRED: 'os-device-required',
  OS_LOGIN: 'login',
  OS_BOOT: 'boot',
  OS_EXTERNAL: 'external',
  OS_SLEEP: 'sleep',
  FS_BACKGROUND: 'background',
} as const;
