import {SeasonalTheme} from './seasonal.models';

/** Planning seeds only: verification is not calendar approval or publication. */
export interface SeasonalPlan {
  readonly id: string;
  readonly holidayLabel: string;
  readonly year: number;
  readonly titleLine1: string;
  readonly titleLine2: string;
  readonly description: string;
  readonly observanceNote: string;
  readonly learnMoreUrl: string | null;
  readonly displayStart: string;
  readonly displayEnd: string;
  readonly theme: SeasonalTheme;
  readonly reflective: boolean;
  readonly dateStatus: 'verified' | 'needs-review';
}

function plan(value: SeasonalPlan): SeasonalPlan {
  return Object.freeze(value);
}

/**
 * Broad U.S. and international starting set, checked on September 30, 2026.
 * Civil display windows are editorial. Empty dates await community review.
 * Keep calendar approval false when converting these plans into editions.
 */
export const SEASONAL_PLANS: readonly SeasonalPlan[] = Object.freeze([
  plan({
    id: 'mlk-day-2027',
    holidayLabel: 'Martin Luther King Jr. Day',
    year: 2027,
    titleLine1: 'Make room',
    titleLine2: 'for service.',
    description: 'A quieter moment for community, justice, and the work of caring for one another.',
    observanceNote: 'The U.S. federal holiday honoring Martin Luther King Jr. falls on January 18, 2027.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-01-18',
    displayEnd: '2027-01-18',
    theme: 'solstice',
    reflective: true,
    dateStatus: 'verified',
  }),
  plan({
    id: 'lunar-new-year-2027',
    holidayLabel: 'Lunar New Year',
    year: 2027,
    titleLine1: 'A new',
    titleLine2: 'beginning.',
    description: 'Gather a little hope, good company, and curiosity for the year ahead.',
    observanceNote: 'The first day of the Chinese lunisolar new year is February 6, 2027; communities use different calendars and celebration periods. This is an editorial display window.',
    learnMoreUrl: 'https://www.info.gov.hk/gia/general/202605/15/P2026051400300.htm',
    displayStart: '2027-02-06',
    displayEnd: '2027-02-09',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'valentines-day-2027',
    holidayLabel: 'Valentine’s Day',
    year: 2027,
    titleLine1: 'A little',
    titleLine2: 'connection.',
    description: 'Celebrate kindness, friendship, and the people who make ordinary days brighter.',
    observanceNote: 'Valentine’s Day falls on February 14; the surrounding dates are an editorial display window.',
    learnMoreUrl: 'https://www.loc.gov/item/today-in-history/february-14/',
    displayStart: '2027-02-12',
    displayEnd: '2027-02-14',
    theme: 'christmas',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'presidents-day-2027',
    holidayLabel: 'Presidents’ Day / Washington’s Birthday',
    year: 2027,
    titleLine1: 'A little',
    titleLine2: 'perspective.',
    description: 'Pause for civic history, thoughtful questions, and a wider view.',
    observanceNote: 'The U.S. federal holiday is named Washington’s Birthday and falls on February 15, 2027; Presidents’ Day is a commonly used label.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-02-15',
    displayEnd: '2027-02-15',
    theme: 'solstice',
    reflective: true,
    dateStatus: 'verified',
  }),
  plan({
    id: 'mardi-gras-2027',
    holidayLabel: 'Mardi Gras',
    year: 2027,
    titleLine1: 'Let a little',
    titleLine2: 'joy in.',
    description: 'Follow bright sparks of music, creativity, and community celebration.',
    observanceNote: 'Mardi Gras Day in New Orleans is February 9, 2027; this shorter editorial window is not the full Carnival season.',
    learnMoreUrl: 'https://www.neworleans.com/events/holidays-seasonal/mardi-gras/future-mardi-gras-dates/',
    displayStart: '2027-02-06',
    displayEnd: '2027-02-09',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'ramadan-2027',
    holidayLabel: 'Ramadan',
    year: 2027,
    titleLine1: 'Room for',
    titleLine2: 'reflection.',
    description: 'Make room for reflection, generosity, and the people around you.',
    observanceNote: 'The 2027 display dates await review against the chosen community’s lunar authority; local announcements and observance boundaries can differ.',
    learnMoreUrl: 'https://fiqhcouncil.org/',
    displayStart: '',
    displayEnd: '',
    theme: 'solstice',
    reflective: true,
    dateStatus: 'needs-review',
  }),
  plan({
    id: 'holi-2027',
    holidayLabel: 'Holi',
    year: 2027,
    titleLine1: 'A little',
    titleLine2: 'more color.',
    description: 'Welcome renewal, joyful connection, and the creativity people bring together.',
    observanceNote: 'The 2027 dates and regional observance context await review; no exact display dates are assumed.',
    learnMoreUrl: 'https://www.hinduamerican.org/community/hindu-holidays-guide',
    displayStart: '',
    displayEnd: '',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'needs-review',
  }),
  plan({
    id: 'eid-al-fitr-2027',
    holidayLabel: 'Eid al-Fitr',
    year: 2027,
    titleLine1: 'Good things,',
    titleLine2: 'shared.',
    description: 'Celebrate generosity, connection, and the joy of gathering with others.',
    observanceNote: 'The 2027 display dates await confirmation from the chosen community’s lunar authority; Eid observance can vary by locality.',
    learnMoreUrl: 'https://fiqhcouncil.org/',
    displayStart: '',
    displayEnd: '',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'needs-review',
  }),
  plan({
    id: 'st-patricks-day-2027',
    holidayLabel: 'St Patrick’s Day',
    year: 2027,
    titleLine1: 'Good company,',
    titleLine2: 'wider stories.',
    description: 'Find a little music, curiosity, and connection in Irish heritage and culture.',
    observanceNote: 'St Patrick’s Day falls on March 17 each year; the surrounding dates are an editorial window, not a claim about every community’s festival.',
    learnMoreUrl: 'https://www.ireland.ie/en/st-patricks-day-2026/everything-you-need-to-know-about-st-patricks-day/',
    displayStart: '2027-03-15',
    displayEnd: '2027-03-17',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'easter-western-2027',
    holidayLabel: 'Easter · Western calendar',
    year: 2027,
    titleLine1: 'Room for',
    titleLine2: 'renewal.',
    description: 'Gather a little hope, kindness, and wonder as the season turns.',
    observanceNote: 'Western Easter Sunday falls on March 28, 2027; Eastern Christian observance dates may differ. The March 26–28 display is editorial.',
    learnMoreUrl: 'https://bible.usccb.org/bible/readings/032827.cfm',
    displayStart: '2027-03-26',
    displayEnd: '2027-03-28',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'passover-2027',
    holidayLabel: 'Passover',
    year: 2027,
    titleLine1: 'Stories carried',
    titleLine2: 'forward.',
    description: 'Make room for memory, freedom, and the stories shared across generations.',
    observanceNote: 'In the Diaspora, Passover begins at sundown April 21 and ends at nightfall April 29, 2027; Israel’s schedule differs. Civil display dates do not simulate observance.',
    learnMoreUrl: 'https://www.hebcal.com/holidays/pesach-2027',
    displayStart: '2027-04-21',
    displayEnd: '2027-04-29',
    theme: 'hanukkah',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'earth-day-2027',
    holidayLabel: 'Earth Day',
    year: 2027,
    titleLine1: 'A little',
    titleLine2: 'care for home.',
    description: 'Notice the living world around us and the small choices that help it thrive.',
    observanceNote: 'Earth Day is observed on April 22 each year; the surrounding dates are an editorial display window.',
    learnMoreUrl: 'https://www.earthday.org/history/',
    displayStart: '2027-04-20',
    displayEnd: '2027-04-22',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'mothers-day-us-2027',
    holidayLabel: 'Mother’s Day · U.S.',
    year: 2027,
    titleLine1: 'Care worth',
    titleLine2: 'celebrating.',
    description: 'Celebrate mothers, caregivers, and the many ways people offer care.',
    observanceNote: 'U.S. Mother’s Day is the second Sunday in May, which is May 9 in 2027; observance dates differ internationally.',
    learnMoreUrl: 'https://uscode.house.gov/download/annualhistoricalarchives/pdf/2024/2024usc36.pdf',
    displayStart: '2027-05-07',
    displayEnd: '2027-05-09',
    theme: 'christmas',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'eid-al-adha-2027',
    holidayLabel: 'Eid al-Adha',
    year: 2027,
    titleLine1: 'Generosity,',
    titleLine2: 'together.',
    description: 'Gather around care, generosity, and meaningful connection.',
    observanceNote: 'The 2027 display dates await review against the chosen community’s lunar authority and local observance context.',
    learnMoreUrl: 'https://fiqhcouncil.org/',
    displayStart: '',
    displayEnd: '',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'needs-review',
  }),
  plan({
    id: 'memorial-day-2027',
    holidayLabel: 'Memorial Day · U.S.',
    year: 2027,
    titleLine1: 'A moment',
    titleLine2: 'to remember.',
    description: 'A quieter space to remember those who died in U.S. military service.',
    observanceNote: 'U.S. Memorial Day falls on May 31, 2027; this is a remembrance page without a collection game.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-05-31',
    displayEnd: '2027-05-31',
    theme: 'solstice',
    reflective: true,
    dateStatus: 'verified',
  }),
  plan({
    id: 'pride-month-2027',
    holidayLabel: 'Pride Month',
    year: 2027,
    titleLine1: 'Room to',
    titleLine2: 'be yourself.',
    description: 'Celebrate LGBTQ+ lives, creativity, belonging, and the work of making room for everyone.',
    observanceNote: 'June is LGBTQ+ Pride Month in the United States; events and observances vary between communities.',
    learnMoreUrl: 'https://www.loc.gov/lgbt-pride-month/',
    displayStart: '2027-06-01',
    displayEnd: '2027-06-30',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'juneteenth-2027',
    holidayLabel: 'Juneteenth',
    year: 2027,
    titleLine1: 'Freedom,',
    titleLine2: 'carried forward.',
    description: 'Make room for Black history, community, joy, and the continuing work of freedom.',
    observanceNote: 'Juneteenth is June 19; in 2027 the federal workplace holiday is observed June 18. This display window includes both dates.',
    learnMoreUrl: 'https://nmaahc.si.edu/explore/stories/historical-legacy-juneteenth',
    displayStart: '2027-06-18',
    displayEnd: '2027-06-19',
    theme: 'kwanzaa',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'summer-solstice-2027',
    holidayLabel: 'Summer Solstice',
    year: 2027,
    titleLine1: 'The longest',
    titleLine2: 'light.',
    description: 'Follow a little wonder into the bright stretch of the year.',
    observanceNote: 'The June 2027 solstice is June 21 at 14:11 Universal Time, or 10:11 a.m. EDT. This is Northern Hemisphere summer; the Southern Hemisphere enters winter.',
    learnMoreUrl: 'https://aa.usno.navy.mil/calculated/seasons?dst=false&submit=Get+Data&tz=0&tz_label=false&tz_sign=0&year=2027',
    displayStart: '2027-06-20',
    displayEnd: '2027-06-22',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'fathers-day-us-2027',
    holidayLabel: 'Father’s Day · U.S.',
    year: 2027,
    titleLine1: 'Good guidance,',
    titleLine2: 'shared.',
    description: 'Celebrate fathers, caregivers, and the encouragement people pass along.',
    observanceNote: 'U.S. Father’s Day is the third Sunday in June, which is June 20 in 2027; observance dates differ internationally.',
    learnMoreUrl: 'https://uscode.house.gov/statutes/pl/92/278.pdf',
    displayStart: '2027-06-18',
    displayEnd: '2027-06-20',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'independence-day-us-2027',
    holidayLabel: 'Independence Day · U.S.',
    year: 2027,
    titleLine1: 'A wider',
    titleLine2: 'horizon.',
    description: 'Gather a little community, reflection, and hope for what we can build together.',
    observanceNote: 'U.S. Independence Day is July 4; the federal workplace holiday is observed July 5 in 2027. The surrounding display dates are editorial.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-07-02',
    displayEnd: '2027-07-05',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'labor-day-us-2027',
    holidayLabel: 'Labor Day · U.S.',
    year: 2027,
    titleLine1: 'Good work,',
    titleLine2: 'together.',
    description: 'Celebrate the people and shared effort that keep communities moving.',
    observanceNote: 'U.S. Labor Day falls on September 6, 2027; other countries recognize workers on different dates.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-09-03',
    displayEnd: '2027-09-06',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'rosh-hashanah-2027',
    holidayLabel: 'Rosh Hashanah',
    year: 2027,
    titleLine1: 'A thoughtful',
    titleLine2: 'beginning.',
    description: 'Gather a little hope, renewal, and care for the year ahead.',
    observanceNote: 'Rosh Hashanah begins at sundown October 1 and ends at nightfall October 3, 2027; civil display dates do not replace observance times.',
    learnMoreUrl: 'https://www.hebcal.com/holidays/rosh-hashana-2027',
    displayStart: '2027-10-01',
    displayEnd: '2027-10-03',
    theme: 'hanukkah',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'yom-kippur-2027',
    holidayLabel: 'Yom Kippur',
    year: 2027,
    titleLine1: 'Space for',
    titleLine2: 'reflection.',
    description: 'A quiet space for reflection, responsibility, and connection.',
    observanceNote: 'Yom Kippur begins at sundown October 10 and ends at nightfall October 11, 2027; this reflection page has no collection game.',
    learnMoreUrl: 'https://www.hebcal.com/holidays/yom-kippur-2027',
    displayStart: '2027-10-10',
    displayEnd: '2027-10-11',
    theme: 'solstice',
    reflective: true,
    dateStatus: 'verified',
  }),
  plan({
    id: 'indigenous-peoples-day-2027',
    holidayLabel: 'Indigenous Peoples’ Day / Columbus Day',
    year: 2027,
    titleLine1: 'Listen, learn,',
    titleLine2: 'make room.',
    description: 'Make room for Indigenous histories, living cultures, and thoughtful reflection.',
    observanceNote: 'In 2027 the second Monday of October is October 11. Many communities recognize Indigenous Peoples’ Day; the U.S. federal holiday on that date is named Columbus Day.',
    learnMoreUrl: 'https://americanindian.si.edu/nk360/faq/did-you-know',
    displayStart: '2027-10-11',
    displayEnd: '2027-10-11',
    theme: 'harvest',
    reflective: true,
    dateStatus: 'verified',
  }),
  plan({
    id: 'diwali-2027',
    holidayLabel: 'Diwali',
    year: 2027,
    titleLine1: 'A little',
    titleLine2: 'more light.',
    description: 'Gather a little hope, connection, and curiosity around the season of light.',
    observanceNote: 'The 2027 dates and regional or community observance context await review; Diwali traditions and festival periods vary.',
    learnMoreUrl: 'https://www.hinduamerican.org/diwali',
    displayStart: '',
    displayEnd: '',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'needs-review',
  }),
  plan({
    id: 'dia-de-los-muertos-2027',
    holidayLabel: 'Día de los Muertos',
    year: 2027,
    titleLine1: 'Memory,',
    titleLine2: 'held with care.',
    description: 'Honor the stories, love, and Mexican cultural traditions that keep memories close.',
    observanceNote: 'Día de los Muertos is celebrated November 1–2; this edition is a respectful cultural invitation rather than an ofrenda or ritual simulation.',
    learnMoreUrl: 'https://www.gob.mx/inafed/articulos/dia-de-muertos-tradicion-mexicana-que-trasciende-en-el-tiempo',
    displayStart: '2027-11-01',
    displayEnd: '2027-11-02',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'veterans-day-2027',
    holidayLabel: 'Veterans Day · U.S.',
    year: 2027,
    titleLine1: 'A moment',
    titleLine2: 'of respect.',
    description: 'Make room for gratitude, listening, and respect for U.S. military veterans.',
    observanceNote: 'U.S. Veterans Day is November 11; this reflection page has no collection game.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-11-11',
    displayEnd: '2027-11-11',
    theme: 'solstice',
    reflective: true,
    dateStatus: 'verified',
  }),
  plan({
    id: 'scary-christmas-2027',
    holidayLabel: 'Halloween · Scary Christmas',
    year: 2027,
    titleLine1: 'Scary',
    titleLine2: 'Christmas.',
    description: 'A little spooky, a little cosmic, and a fresh lantern of discoveries.',
    observanceNote: 'Halloween is October 31; October 1–November 1 is Colin’s editorial Scary Christmas display window, independent of the preserved 2026 collection.',
    learnMoreUrl: 'https://guides.loc.gov/chronicling-america-halloween',
    displayStart: '2027-10-01',
    displayEnd: '2027-11-01',
    theme: 'halloween',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'thanksgiving-2027',
    holidayLabel: 'Thanksgiving · U.S.',
    year: 2027,
    titleLine1: 'Good things,',
    titleLine2: 'gathered.',
    description: 'Notice good company, shared care, and the small things worth appreciating.',
    observanceNote: 'U.S. Thanksgiving falls on November 25, 2027; the surrounding dates are an editorial display window.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-11-19',
    displayEnd: '2027-11-28',
    theme: 'harvest',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'hanukkah-2027',
    holidayLabel: 'Hanukkah',
    year: 2027,
    titleLine1: 'A little',
    titleLine2: 'brighter.',
    description: 'Make room for light, resilience, and connection across the season.',
    observanceNote: 'Hanukkah begins at sundown December 24, 2027 and ends at nightfall January 1, 2028; civil display dates do not simulate ritual lighting.',
    learnMoreUrl: 'https://www.hebcal.com/holidays/chanukah-2027',
    displayStart: '2027-12-24',
    displayEnd: '2028-01-01',
    theme: 'hanukkah',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'winter-solstice-2027',
    holidayLabel: 'Winter Solstice',
    year: 2027,
    titleLine1: 'The longest',
    titleLine2: 'night.',
    description: 'Find a little calm, curiosity, and light as the season turns.',
    observanceNote: 'The December solstice is December 22, 2027 at 02:42 Universal Time, equivalent to December 21 at 9:42 p.m. EST. This is Northern Hemisphere winter.',
    learnMoreUrl: 'https://aa.usno.navy.mil/calculated/seasons?dst=false&submit=Get+Data&tz=0&tz_label=false&tz_sign=0&year=2027',
    displayStart: '2027-12-20',
    displayEnd: '2027-12-22',
    theme: 'solstice',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'christmas-2027',
    holidayLabel: 'Christmas',
    year: 2027,
    titleLine1: 'Cosmic',
    titleLine2: 'Christmas.',
    description: 'Gather a little wonder, goodwill, and connection beneath wider skies.',
    observanceNote: 'Christmas Day is December 25; the U.S. federal workplace holiday is observed December 24 in 2027. Traditions and observance dates vary between communities.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-12-13',
    displayEnd: '2027-12-25',
    theme: 'christmas',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'kwanzaa-2027',
    holidayLabel: 'Kwanzaa',
    year: 2027,
    titleLine1: 'Together,',
    titleLine2: 'we glow.',
    description: 'Make room for African and African American heritage, community, purpose, and creativity.',
    observanceNote: 'Kwanzaa is observed December 26–January 1; this is a cultural invitation, not a reenactment of observance.',
    learnMoreUrl: 'https://nmaahc.si.edu/explore/moments/kwanzaa',
    displayStart: '2027-12-26',
    displayEnd: '2028-01-01',
    theme: 'kwanzaa',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'new-year-2028',
    holidayLabel: 'New Year',
    year: 2028,
    titleLine1: 'Next',
    titleLine2: 'orbit.',
    description: 'Carry a few bright ideas and a little hope into the adventures still to come.',
    observanceNote: 'This editorial window surrounds January 1, 2028 in the Gregorian calendar; the U.S. federal workplace holiday is observed December 31, 2027.',
    learnMoreUrl: 'https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/',
    displayStart: '2027-12-31',
    displayEnd: '2028-01-03',
    theme: 'new-year',
    reflective: false,
    dateStatus: 'verified',
  }),
  plan({
    id: 'vesak-2027',
    holidayLabel: 'Vesak',
    year: 2027,
    titleLine1: 'Compassion,',
    titleLine2: 'carried forward.',
    description: 'Make room for kindness, calm, and thoughtful connection.',
    observanceNote: 'The 2027 display dates await review with the intended Buddhist community; calendars and local observance dates can differ.',
    learnMoreUrl: 'https://www.un.org/en/observances/vesak-day',
    displayStart: '',
    displayEnd: '',
    theme: 'solstice',
    reflective: false,
    dateStatus: 'needs-review',
  }),
]);
